language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
script: make test

install:
    - pip install \
          `python -c 'from setup import META; print(" ".join(META["extras_require"]["testing"]))'`
